/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.everage.eshop;

import com.everage.eshop.EverageApplication;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
//    @Test void appHasAGreeting() {
//        EverageApplication classUnderTest = new App();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//    }
}
